name: Get New Videos

on:
  schedule:
    # This example runs every day at 00:00 UTC
    # Use crontab.guru to help define your schedule
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run the script manually for testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.13' # Specify your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
          BOSS_CR_WEBHOOK: ${{ secrets.BOSS_CR_WEBHOOK }}
        run: python notifications.py # Replace with your script name
      
      - name: Commit and push database
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add default.db
          # The '|| exit 0' prevents the action from failing if there are no new videos to commit
          git commit -m "Automated database update: added new videos" || exit 0
          git push
